language: node_js
install:
- nvm install 10.16.2
- nvm use 10.16.2
- npm install
- npm install mocha -g
script:
- mocha -r esm test/domain
after_success:
- echo Build Succeded
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  region: us-west-1
  app: spiderman-bot
  env: spidermanbot-node-env
  bucket_name: elasticbeanstalk-us-west-1-113021065873