language: node_js
install:
- nvm install 10.16.2
- nvm use 10.16.2
- npm install
- npm install mocha -g
script:
- mocha -r esm test/domain
after_success:
- echo Build Succeded
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: Encrypted <GrSjLf3jtOMIWE7qLNe8KTo84/j+ghV8BwHyanyf0/b4N9TUsQf0FvvzPW0LP5XKGg3dlAlQz89BPVFPa8egoBHCX8pPd5lBid4aQscDPRehSflydpt3QDs8JcdoSThEldg4BTAJJMlzPX2CQp892yz0X4/N2COn90tZMWiRclkKf0m5QPIz9BKMlcbPmfRCqsEBJFVjq8SciRlNPLUaDdJqNA6fPQDwCSX1EsgMjyvt7k4KtAcodEV1C5L2dpA20LnzhheTTOvjqPasD4l5K27NWqeI48AlC3E1dV3F573eu+5lsLxGnaXhsaWJFUXdcUzFo4FbkoAzBY+gXtOocdoOZ+mtPWKG5HGWKPzhfHtESn5p+5LiWEVbuBJCi73O6J0RxPMjxeqE5LIHQUK3F/y/vQdLe9kbAYM24yKgbisN3RyJywez/NN5UJ7Y2N6Y/88ckRikH4w5XD6BUm3/k9+bhXyWVPV9VbOhyHzgA+6qlARCei4ftIpVjEDfjEF3oFp1Z52nrzQ6QTtHkCpMtHtIOKoVqpqyOqACkqx57zYVp6WQ0ZDS8/W07aTrr32SFir7zeiLPvkQuMkrLgKfNdbmATpLjWEmttQ8dcy5DFjaBI9cuAePYZm4r2cHdzxZlQSAmYv57h2WVijjCVwsaTPmA8m2c/zGW+NLux4Jp+w=>=
  secret_access_key:
    secure: Encypted <WCMwyhwKCpgFhjDtjpoUOO42cxmSa9HTfVLVoMTLAEFfL+/iRloeDmgp7VEri58mXHeTG6rFpQRe3uKiee/KhLEPHgT9eGO5mbLrm3ZvtugA3g6Cggxx7Bh7D/W2iBXXfZv9zsu+nryM0WEXcIx7sAQKHuLYvBnavbu8NsIgBT+TBzO2ZJ+rnhPZUQZE30DVzR5/ReCP4iwO/idnZG7PbiSuS24yOZ0ez+4yf+qst5h8eg7ZqlLGhg1/+5dvqThRy38UXBPIqT0LnWRcVNIOMbWXscGbYRKeHO7KoUf2/XBCGGjHR1D2b/Z9GqgxDh/HVVUxKmqiHkYSHiW1xIx9JWuJwe8egru4Cm3hq3kiGISFOcVrIW5dZZc1MZkW1knghbuakyfIe3UKLXdkOphtnQoop/Lmvpig7hwstW36Ki4PHI71zGruY862DqlHOwkRubkRez8bxrf53HL22BMf3MR9qxHZJwXBzxKtxg176EUoumdakyOvfVrfzsOpxQxwhloRO1CtTegu7sOzBinTVMhJqzwDmYP8tHSR5Z+nl2ScSFXjGa/v8eia2GHvh7YTWrbMkucPHHcqqb9ovsO73UIgfvjSxvqPduC8blwbxkHS0oUrZ8q4n5NLNzN09XcqIL/6hA+4jGzvrJo4ns1wTdHAQ4y6u4w005dPJMBv/F8=>=
  region: us-west-1
  app: spiderman-bot
  env: spidermanbot-node-env
  bucket_name: elasticbeanstalk-us-west-1-113021065873